website/models/message.py
from .. import db
from sqlalchemy.sql import func

    
class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    sender_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    receiver_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime(timezone=True), default=func.now())
     
    sender = db.relationship('User', foreign_keys=[sender_id], backref='sent_messages')
    receiver = db.relationship('User', foreign_keys=[receiver_id], backref='received_messages')

    

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Profile, User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user



auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash(['Sesion iniciada correctamente!'], category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash(['Contraseña incorrecta, intente otra vez.'], category='error')
        else:
            flash(['El correo no existe.'], category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        username = request.form.get('username')
        
        # Verificar si el correo ya está registrado
        user_by_email = User.query.filter_by(email=email).first()
        
        # Verificar si el nombre de usuario ya está registrado
        user_by_username = User.query.filter_by(username=username).first()
        
        errors = []
        if user_by_email:
            errors.append('Error: Este correo ya esta registrado.')
        if user_by_username:
            errors.append('Error: Este usuario ya esta registrado.')
        if len(username) < 4:
            errors.append('Error: El nombre de usuario debe ser mayor a 3 caracteres.')
        if len(email) < 4:
            errors.append('Error: El correo debe ser mayor a 3 caracteres.')
        if len(first_name) < 2:
            errors.append('Error: El Nombre debe ser mayor a 1 caracter.')
        if password1 != password2:
            errors.append('Error: Las contraseñas no coinciden.')
        if len(password1) < 7:
            errors.append('Error: La contraseña debe ser de al menos 7 caracteres.')
        
        if len(errors) > 0:
            flash(errors, category='danger')    
        else:
            new_user = User(email=email, first_name=first_name, username=username, password=generate_password_hash(
                password1, method='pbkdf2:sha256'))
            #new_user = User(email=email, first_name=first_name, password=generate_password_hash(
            #    password1, method='sha256')) # the method "sha256" is deprecated, use pbkdf2:sha256
            db.session.add(new_user)
            db.session.commit()
                
            # Crear un perfil asociado
            new_profile = Profile(user_id=new_user.id)
            
            login_user(new_user, remember=True)
            msg = ['Cuenta creada correctamente!']
            flash(msg, category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views/all_views.py
# website/views/comment_views.py

from flask import Blueprint, redirect, request, flash, url_for
from flask_login import login_required, current_user
from ..services.comment_service import add_comment, delete_comment, like_comment, edit_comment

comment_views = Blueprint('comment_views', __name__)

@comment_views.route('/comment/<int:publication_id>', methods=['POST'])
@login_required
def comment(publication_id):
    comment_content = request.form.get('comment')
    parent_comment_id = request.form.get('parent_id')  # Puede ser None si es un nuevo comentario

    print(f"Comentario: {comment_content}, Parent ID: {parent_comment_id}")  # Para depuración

    new_comment = add_comment(publication_id, comment_content, parent_comment_id)
    if new_comment is None:
        return redirect(url_for('home_views.home'))  # Si no se agrega el comentario, redirige

    return redirect(url_for('home_views.home'))

@comment_views.route('/delete-comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment_route(comment_id):
    delete_comment(comment_id)
    return redirect(url_for('home_views.home'))

@comment_views.route('/like-comment/<int:comment_id>', methods=['POST'])
@login_required
def like_comment_route(comment_id):
    success, play_cuak_sound = like_comment(comment_id)
    return redirect(url_for('home_views.home', play_cuak=play_cuak_sound))

@comment_views.route('/edit-comment/<int:comment_id>', methods=['POST'])
@login_required
def edit_comment_route(comment_id):
    new_comment_content = request.form.get('comment')
    edit_comment(comment_id, new_comment_content)
    return redirect(url_for('home_views.home'))


# website/views/follow_views.py

from flask import Blueprint, redirect, request, flash, url_for
from flask_login import login_required, current_user
from ..services.follow_service import follow_user, unfollow_user

follow_views = Blueprint('follow_views', __name__)

# Nueva ruta para seguir a un usuario
@follow_views.route('/follow/<int:user_id>', methods=['POST', 'GET'])
@login_required
def follow_route(user_id):
    follow_user(user_id)
    return redirect(request.referrer or 'home_views.home')

# Ruta para dejar de seguir a un usuario
@follow_views.route('/unfollow/<int:user_id>', methods=['POST'])
@login_required
def unfollow_route(user_id):
    unfollow_user(user_id)
    return redirect(request.referrer or 'home_views.home')


# website/views/home_views.py

from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from ..services.home_service import create_post, load_user_posts

home_views = Blueprint('home_views', __name__)

@home_views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    playCuakSound = False
    if request.method == 'POST': 
        post_content = request.form.get('post')
        content_type = request.form.get('content_type')  # Obtener el tipo de contenido
        image_url = request.form.get('image_url')  # Obtener la URL de la imagen
        video_url = request.form.get('video_url')  # Obtener la URL del video

        # Llamamos a la función del servicio para crear la publicación
        new_post, playCuakSound = create_post(post_content, content_type, image_url, video_url)

        if not new_post:
            return redirect(url_for('home_views.home'))  # Si no se crea la publicación, redirigimos de vuelta

    # Llamamos a la función del servicio para cargar las publicaciones
    all_posts = load_user_posts()

    return render_template("home.html", user=current_user, posts=all_posts, play_cuak=playCuakSound)

# website/views/messages_views.py

from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from ..services.messages_service import get_followed_users, get_messages, send_message, get_user_info

messages_views = Blueprint('messages_views', __name__)

@messages_views.route('/messages')
@login_required
def mensajes():
    # Obtener los usuarios seguidos por el usuario actual
    followed_users = get_followed_users(current_user.id)

    # Obtener los mensajes entre el usuario actual y los usuarios seguidos
    messages = []
    for user in followed_users:
        user_messages = get_messages(current_user.id, user.id)  # Obtener mensajes entre el usuario actual y el seguido
        messages.append((user, user_messages))

    return render_template('messages.html', followed_users=followed_users, messages=messages, user=current_user)


@messages_views.route('/get_messages/<int:other_user_id>', methods=['GET'])
@login_required
def get_messages_route(other_user_id):
    user_id = current_user.id  # Asumiendo que estás utilizando Flask-Login
    messages = get_messages(user_id, other_user_id)
    
    # Obtener información de los usuarios (nombre y username)
    users = get_user_info([user_id, other_user_id])

    # Retorna los mensajes en formato JSON
    return jsonify([{
        'sender_id': message.sender_id,
        'receiver_id': message.receiver_id,
        'sender_first_name': users[message.sender_id]['first_name'],
        'sender_username': users[message.sender_id]['username'],
        'content': message.content,
        'timestamp': message.timestamp.strftime('%Y-%m-%d %H:%M:%S')
    } for message in messages])


@messages_views.route('/send_message', methods=['POST'])
@login_required
def send_message_route():
    data = request.get_json()
    receiver_id = data.get('receiver_id')
    content = data.get('content')
    sender_id = current_user.id  # Asumiendo que estás usando Flask-Login
    
    send_message(sender_id, receiver_id, content)
    return jsonify({"message": "Mensaje enviado con éxito"})


# website/views/publication_views.py 

from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from .. import db
from ..services.publication_service import delete_publication, like_publication, edit_publication, send_message, get_publication_with_details

publication_views = Blueprint('publication_views', __name__)

@publication_views.route('/delete-publication/<int:publication_id>', methods=['POST'])
@login_required
def delete_publication_route(publication_id):
    delete_publication(publication_id)
    return redirect(url_for('home_views.home'))


@publication_views.route('/like/<int:publication_id>', methods=['POST'])
@login_required
def like_publication_route(publication_id):
    playCuakSound = like_publication(publication_id)
    return redirect(request.referrer or url_for('home_views.home', play_cuak=playCuakSound))


@publication_views.route('/post/<int:post_id>', methods=['GET'])
@login_required
def view_post(post_id):
    individual_post = get_publication_with_details(post_id)
    return render_template("view_post.html", user=current_user, _publication=individual_post)


@publication_views.route('/edit-publication/<int:publication_id>', methods=['POST'])
@login_required
def edit_publication_route(publication_id):
    new_content = request.form.get('post')
    image_url = request.form.get('image_url')
    video_url = request.form.get('video_url')
    content_type = request.form.get('content_type')

    edit_publication(publication_id, new_content, image_url, video_url, content_type)
    return redirect(url_for('home_views.home'))


# website/views/user_views.py

from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from ..services.user_service import get_user_profile, update_user_profile, get_following_users, get_all_users
from ..models.user import User

user_views = Blueprint('user_views', __name__)

@user_views.route('/profile/<int:user_id>', methods=['GET'])
@login_required
def profile(user_id):
    playCuakSound = False
    user, followers_count, following_count, posts, posts_count = get_user_profile(user_id)

    is_current_user = (current_user.id == user.id)
    is_following = current_user.id in [follow.follower_id for follow in user.followers]

    playCuakSound = True
    return render_template('profile.html', user=user, followers_count=followers_count,
                           following_count=following_count, posts=posts,
                           posts_count=posts_count, is_current_user=is_current_user,
                           is_following=is_following, play_cuak=playCuakSound)

@user_views.route('/edit-profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
def edit_profile(user_id):
    playCuakSound = False
    user = User.query.get_or_404(user_id)

    if user.id != current_user.id:
        flash(['No tienes permiso para editar este perfil.'], category='error')
        return redirect(url_for('home_views.home'))

    profile = user.profile  # Obtiene el perfil directamente desde el usuario

    if request.method == 'POST':
        username = request.form.get('username')
        first_name = request.form.get('first_name')
        bio = request.form.get('bio')
        background_picture = request.form.get('background_picture')

        print("Datos del usuario antes de la edición:")
        print("Username:", user.username)
        print("Name:", user.first_name)
        print("Bio:", profile.bio)
        print("Profile Picture:", user.profile_picture)
        print("Background Picture:", profile.background_picture)

        user, profile = update_user_profile(user.id, first_name, bio, background_picture)

        print("Datos del usuario después de la edición:")
        print("Username:", user.username)
        print("Name:", user.first_name)
        print("Bio:", profile.bio)
        print("Profile Picture:", user.profile_picture)
        print("Background Picture:", profile.background_picture)

        playCuakSound = True
        flash(['Perfil actualizado correctamente!'], category='success')
        return redirect(url_for('user_views.profile', user_id=user.id, play_cuak=playCuakSound))

website/views/home_views.py
# website/views/home_views.py

from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from ..services.home_service import create_post, load_user_posts

home_views = Blueprint('home_views', __name__)

@home_views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    playCuakSound = False
    if request.method == 'POST': 
        post_content = request.form.get('post')
        content_type = request.form.get('content_type')  # Obtener el tipo de contenido
        image_url = request.form.get('image_url')  # Obtener la URL de la imagen
        video_url = request.form.get('video_url')  # Obtener la URL del video

        # Llamamos a la función del servicio para crear la publicación
        new_post, playCuakSound = create_post(post_content, content_type, image_url, video_url)

        if not new_post:
            return redirect(url_for('home_views.home'))  # Si no se crea la publicación, redirigimos de vuelta

    # Llamamos a la función del servicio para cargar las publicaciones
    all_posts = load_user_posts()

    return render_template("home.html", user=current_user, posts=all_posts, play_cuak=playCuakSound)

website/views/messages_views.py
# website/views/messages_views.py

from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from ..services.messages_service import get_followed_users, get_messages, send_message, get_user_info

messages_views = Blueprint('messages_views', __name__)

@messages_views.route('/messages')
@login_required
def mensajes():
    # Obtener los usuarios seguidos por el usuario actual
    followed_users = get_followed_users(current_user.id)

    # Obtener los mensajes entre el usuario actual y los usuarios seguidos
    messages = []
    for user in followed_users:
        user_messages = get_messages(current_user.id, user.id)  # Obtener mensajes entre el usuario actual y el seguido
        messages.append((user, user_messages))

    return render_template('messages.html', followed_users=followed_users, messages=messages, user=current_user)


@messages_views.route('/get_messages/<int:other_user_id>', methods=['GET'])
@login_required
def get_messages_route(other_user_id):
    user_id = current_user.id  # Asumiendo que estás utilizando Flask-Login
    messages = get_messages(user_id, other_user_id)
    
    # Obtener información de los usuarios (nombre y username)
    users = get_user_info([user_id, other_user_id])

    # Retorna los mensajes en formato JSON
    return jsonify([{
        'sender_id': message.sender_id,
        'receiver_id': message.receiver_id,
        'sender_first_name': users[message.sender_id]['first_name'],
        'sender_username': users[message.sender_id]['username'],
        'content': message.content,
        'timestamp': message.timestamp.strftime('%Y-%m-%d %H:%M:%S')
    } for message in messages])


@messages_views.route('/send_message', methods=['POST'])
@login_required
def send_message_route():
    data = request.get_json()
    receiver_id = data.get('receiver_id')
    content = data.get('content')
    sender_id = current_user.id  # Asumiendo que estás usando Flask-Login
    
    send_message(sender_id, receiver_id, content)
    return jsonify({"message": "Mensaje enviado con éxito"})

website/templates/post_macros.html
{% macro render_publications(post, current_user) %}
<div class="list-group-item">
  <div class="media">
    <span style="width: min-content;" class="d-inline-flex flex-column justify-content-between">
      <a href="{{ url_for('user_views.profile', user_id=post.user.id) }}">
        <img src="{{ post.user.profile_picture }}" alt="{{ post.user.first_name }}" class="mr-3 rounded-circle"
          style="width: 50px; height: 50px;">
      </a>

      <!-- Flecha de toggle para comentarios -->
      <button class="btn btn-link toggle-comments-btn px-0 mr-3" onclick="toggleComments({{ post.id }})">
        <span id="toggleText-{{ post.id }}">Ocultar Hilo</span> <!-- Texto inicial en "Ocultar Hilo" -->
        <i class="fa fa-arrow-up" id="toggleArrow-{{ post.id }}"></i> <!-- Flecha hacia arriba por defecto -->
      </button>
    </span>

    <span class="w-100 d-flex flex-column justify-content-start align-items-center">
      <div class="media-body w-100 d-inline-flex flex-column">
        <h5 class="mt-0 d-inline-flex justify-content-between">
          <span id="userName" style="cursor: pointer;" onclick="goToUserProfile('{{ post.user.id }}')">
            {{ post.user.first_name }}
            <span style="font-size: 14px; font-style:italic; font-weight:lighter;">
              @{{ post.user.username }}
            </span>

            <!-- Enlace para ver la publicación individual -->
            <a href="{{ url_for('publication_views.view_post', post_id=post.id) }}" class="btn btn-link d-none d-md-inline">
              <i class="fa-brands fa-readme"></i>
              Ver publicación
            </a>
          </span>
    </span>
    <small style="font-size: 12px;" class="text-muted d-inline-flex align-items-baseline">
      {{ post.date.strftime('%d-%m-%Y %I:%M:%S %p') }}
      <form method="POST" action="{{ url_for('publication_views.delete_publication_route', publication_id=post.id) }}"
        style="display:inline;">
        {% if post.user_id == current_user.id %}
        <button type="submit" class="btn btn-link text-danger delete-comment-btn"
          onclick="return confirmDelete(event);">
          <i class="fas fa-trash-alt"></i>
        </button>
        {% endif %}
      </form>
      <span class="d-inline">
        {% if post.user_id == current_user.id %}
        <button class="btn btn-link" onclick="openEditPostModal(
                  {{ post.id }},
                  '{{ post.data.replace("'", "\\'").replace('"', ' \\"').replace('\n', '\\n' ).replace('\r', '' )
          }}', '{{ (post.image_url or "").replace("'", " \\'") }}', '{{ (post.video_url or "").replace("'", " \\'")
          }}', '{{ post.content_type.replace("'", " \\'") }}' )">
          <i class="fa-solid fa-pen-to-square"></i>
        </button>
        {% endif %}
      </span>
    </small>

    </h5>
    <span>
      {% if post.content_type == 'image' and post.image_url %}
      <img src="{{ post.image_url }}" alt="" class="img-fluid mt-2">
      {% elif post.content_type == 'video' and post.video_url %}
      <div class="responsive-video">
        <iframe src="{{ post.video_url }}" frameborder="0" allowfullscreen></iframe>
      </div>
      {% endif %}

    </span>
    <div class="post-content">{{ post.data }}</div>
  </div>

  <!-- Botones de "Me gusta" y comentario -->
  <span class="d-flex justify-content-start align-items-center w-100">
    <!--
        <form method="POST" action="{{ url_for('publication_views.like_publication_route', publication_id=post.id) }}" class="d-inline-flex">
      <button type="submit" class="btn btn-link text-primary">
        <i class="fas fa-thumbs-up" style="color: {{ 'blue' if post.liked else 'lightgray' }};"></i>
        {{ post.likes_count }}
      </button>
    </form>
    -->
    <button type="button" class="btn btn-link text-primary" onclick="likePost({{ post.id }})">
      <i id="like-icon-{{ post.id }}" class="fas fa-thumbs-up" style="color: {{ 'blue' if post.liked else 'lightgray' }};"></i>
      <span id="likes-count-{{ post.id }}">{{ post.likes_count }}</span> Likes
    </button>
    
    <button onclick="toggleCommentForm({{ post.id }})" class="btn btn-link">
      <i class="fa-solid fa-comment"></i> {{ post.comments|length }}
    </button>


    <!-- Enlace para ver la publicación individual -->
    <a href="{{ url_for('publication_views.view_post', post_id=post.id) }}" class="btn btn-link d-inline d-md-none">
      <i class="fa-brands fa-readme"></i>
      Ver publicación
    </a>

  </span>

  <!-- Formulario comentar -->
  <div id="commentForm-{{ post.id }}" style="display:none;" class="comment-form mb-3 w-100">
    <form method="POST" action="{{ url_for('comment_views.comment', publication_id=post.id) }}">
      <textarea name="comment" class="form-control" placeholder="Escribe un comentario..." required></textarea>
      <span class="d-flex justify-content-end align-items-center">
        <button type="submit" class="btn btn-primary mt-2"><i class="fas fa-paper-plane"></i></button>
      </span>
    </form>
  </div>
  <!-- Formulario editar Publicacion -->
  <div id="editPostContainer-{{ post.id }}" style="display: none; width: 100%;">
    <form id="editPostForm-{{ post.id }}" method="POST" class="mb-4"
      action="{{ url_for('publication_views.edit_publication_route', publication_id=post.id) }}">
      <textarea name="post" id="editPostContent-{{ post.id }}" class="form-control" placeholder="¿Qué estás pensando?"
        required></textarea>

      <div class="form-group mt-3" id="editImageUrlField-{{ post.id }}" style="display: none;">
        <label for="editImageUrl">URL de Imagen:</label>
        <input type="text" name="image_url" id="editImageUrl-{{ post.id }}" class="form-control"
          placeholder="Ingresa la URL de la imagen">
      </div>

      <div class="form-group mt-3" id="editVideoUrlField-{{ post.id }}" style="display: none;">
        <label for="editVideoUrl">URL de Video:</label>
        <input type="text" name="video_url" id="editVideoUrl-{{ post.id }}" class="form-control"
          placeholder="Ingresa la URL del video">
      </div>

      <div class="d-flex flex-row justify-content-between align-items-start mt-3">
        <div class="form-group">
          <label for="editContentType">Tipo de Publicación:</label>
          <select name="content_type" id="editContentType-{{ post.id }}" class="form-control" required
            onchange="toggleEditUrlFields({{ post.id }})">
            <option value="text">Texto</option>
            <option value="image">Imagen</option>
            <option value="video">Video</option>
          </select>
        </div>
        <span>
          <button type="button" class="btn btn-secondary" onclick="closeEditPostModal({{ post.id }})">Cancelar</button>
          <button type="submit" class="btn btn-primary">
            <i class="fas fa-paper-plane"></i> Guardar cambios
          </button>
        </span>
      </div>
    </form>
  </div>
  </span>
</div>

<!-- Comentarios -->
<div class="comments" id="comments-{{ post.id }}" style="display:block;">
  {% for comment in post.comments if not comment.parent_id %}
  {{ comment_block(comment, current_user) }}
  {% endfor %}
</div>
</div>
{% endmacro %}


{% macro comment_block(comment, current_user, level=0) %}
<div class="media comment-root py-0 my-0">
  <a href="{{ url_for('user_views.profile', user_id=comment.user.id) }}">
    <img src="{{ comment.user.profile_picture }}" alt="{{ comment.user.first_name }}" class="mr-3 mt-3 rounded-circle"
      style="width: 30px; height: 30px;">
  </a>
  <div class="media-body pb-0">
    <span class="d-flex justify-content-between align-items-center">
      <h6 class="d-inline-flex justify-content-between">
        <span id="userName" style="cursor: pointer;" onclick="goToUserProfile('{{ comment.user.id }}')">
          {{ comment.user.first_name }}
          <span style="font-size: 14px; font-style:italic; font-weight:lighter;">
            @{{ comment.user.username }}
          </span>
        </span>
      </h6>
      <small style="font-size: 12px;" class="text-muted">{{ comment.date.strftime('%d-%m-%Y %I:%M:%S %p') }}</small>
    </span>
    <div class="d-flex justify-content-between align-items-center">
      <div class="post-content">{{ comment.data }}</div>


      <span class="d-flex flex-row">
        <!-- Botón de "Me gusta" para el comentario -->
         <!--
        <form method="POST" action="{{ url_for('comment_views.like_comment_route', comment_id=comment.id) }}" class="d-inline-flex">
          <button type="submit" class="btn btn-link text-primary">
            <i class="fas fa-thumbs-up" style="color: {{ 'blue' if comment.liked else 'lightgray' }};"></i>
            {{ comment.likes_count }}
          </button>
        </form>
      -->
        <button type="button" class="btn btn-link text-primary" onclick="likeComment({{ comment.id }})">
          <i id="comment-like-icon-{{ comment.id }}" class="fas fa-thumbs-up" style="color: {{ 'blue' if comment.liked else 'lightgray' }};"></i>
          <span id="comment-likes-count-{{ comment.id }}">{{ comment.likes_count }}</span>
        </button>
        <!-- Botón de "Eliminar" si el usuario realizo el comentario -->
        <button onclick="toggleReplyForm({{ comment.id }})" class="btn btn-link reply-btn"><i
            class="fa-solid fa-reply"></i></button>
        {% if comment.user_id == current_user.id %}
        <form method="POST" action="{{ url_for('comment_views.delete_comment_route', comment_id=comment.id) }}"
          style="display:inline;">
          <button type="submit" class="btn btn-link text-danger delete-comment-btn"
            onclick="return confirmDelete(event);"><i class="fas fa-trash-alt"></i></button>
        </form>

        <span class="d-inline">
          <button class="btn btn-link" onclick="openEditCommentModal(
            {{ comment.id }},
            '{{ comment.data.replace("'", "\\'").replace('"', ' \\"').replace('\n', '\\n' ).replace('\r', '' ) }}' )">
            <i class="fa-solid fa-pen-to-square"></i>
          </button>
        </span>
        {% endif %}
      </span>
    </div>

    <!-- Formulario de respuesta -->
    <div id="replyForm-{{ comment.id }}" style="display:none;" class="reply-form mt-2">
      <form method="POST" action="{{ url_for('comment_views.comment', publication_id=comment.publication_id) }}">
        <input type="hidden" name="parent_id" value="{{ comment.id }}">
        <textarea name="comment" class="form-control mt-2" placeholder="Escribe tu respuesta..." required></textarea>
        <span class="d-flex justify-content-end align-items-center">
          <button type="submit" class="btn btn-primary mt-2"><i class="fas fa-paper-plane"></i></button>
        </span>
      </form>
    </div>
    <!-- Formulario editar respuesta -->
    <div id="editCommentModal-{{ comment.id }}" style="display: none;" class="edit-comment-modal mt-2">
      <form id="editCommentForm-{{ comment.id }}" method="POST" action="{{ url_for('comment_views.edit_comment_route', comment_id=comment.id) }}"  class="mb-4">
        <textarea name="comment" id="editCommentContent-{{ comment.id }}" class="form-control"
          placeholder="Edita tu comentario" required></textarea>
        <br />
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">
            <i class="fas fa-paper-plane"></i> Guardar cambios
          </button>
          <button type="button" class="btn btn-secondary ml-2"
            onclick="closeEditCommentModal({{ comment.id }})">Cancelar</button>
        </div>
      </form>
    </div>

    <!-- Renderiza respuestas recursivamente -->
    {% if comment.replies %}
    {% for reply in comment.replies %}
    {{ comment_block(reply, current_user, level + 1) }}
    {% endfor %}
    {% endif %}
  </div>
</div>


<script>
  function likePost(postId) {
    // Realiza la solicitud AJAX para dar o quitar "me gusta"
    fetch('/like/' + postId, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ postId: postId })
    })
    .then(response => response.json())
    .then(data => {
        // Actualiza el contador de "me gusta"
        const likesCountElement = document.getElementById('likes-count-' + postId);
        if (likesCountElement) {
            likesCountElement.textContent = data.likes_count;
        }

        // Cambia el color del ícono según el estado de "me gusta"
        const likeIcon = document.getElementById('like-icon-' + postId);
        if (likeIcon) {
            likeIcon.style.color = data.playCuakSound ? 'blue' : 'lightgray';
        }
    })
    .catch(error => {
        console.error('Error al dar "me gusta":', error);
    });
  }

  function likeComment(commentId) {
    fetch('/like-comment/' + commentId, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
    })
    .then(response => response.json())
    .then(data => {
        if (data.error) {
            console.error('Error:', data.error);
            return;
        }

        // Actualiza el contador de "likes" en el frontend
        const likesCountElement = document.getElementById('comment-likes-count-' + commentId);
        if (likesCountElement) {
            likesCountElement.textContent = data.likes_count;
        }

        // Cambia el color del ícono dependiendo del estado de "me gusta"
        const likeIcon = document.getElementById('comment-like-icon-' + commentId);
        if (likeIcon) {
            likeIcon.style.color = data.playCuakSound ? 'blue' : 'lightgray';
        }
    })
    .catch(error => {
        console.error('Error al procesar el "me gusta" del comentario:', error);
    });
}


  </script>


{% endmacro %}

website/templates/view_post.html
{% extends "base.html" %}


{% import "post_macros.html" as post_macros %}


{% block content %}
<div class="container">


    <div class="overflow-auto">
        <div class="list-group over" style="min-width: fit-content;">
            
            {{ post_macros.render_publications(_publication, current_user) }}
            
        </div>
    </div>

{% endblock %}